function forwProp_gen(obj, N)
% Forward propagation in nade, where the input is generated by nade itself.
% 
% George Papamakarios, Jun 2015

obj.y = obj.precision(zeros(obj.num_inputs, N, obj.arraytype));
obj.x = obj.precision(zeros(obj.num_inputs, N, obj.arraytype));
obj.h = obj.precision(zeros(obj.num_inputs, obj.num_hidden, N, obj.arraytype));
W = [obj.W' obj.precision(zeros(obj.num_hidden, 1, obj.arraytype))];

a =  obj.c' * obj.precision(ones(1, N, obj.arraytype));

for i = 1:obj.num_inputs
    
    hi = obj.hidden_f(a);
    obj.y(i,:) = obj.sigm(obj.U(i,:) * hi + obj.b(i));
    obj.x(i,:) = obj.precision(rand(1, N, obj.arraytype) < obj.y(i,:));
    a = a + W(:,i) * obj.x(i,:);
    obj.h(i,:,:) = hi;
end

obj.L = sum(obj.x .* log(obj.y) + (1-obj.x) .* log(1-obj.y), 1);

% set flags
obj.done_forwProp = true;
obj.done_backProp = false;
